<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [11]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
from statistics import mean

def get_matrix_size(X):
    a = len(X)
    b = mean([len(e) for e in X])
    if b == len(X[1]):
        return (a, b)
    else:
        return None

# here A and B are list of lists
def matrix_mul(A, B):
    size_A = get_matrix_size(A)
    size_B = get_matrix_size(B)
    
    if size_A is None or size_B is None:
        return 'A*B = Not possible'
    elif size_A[1] != size_B[0]:
        return 'A*B = Not possible'
    else:
        acc = []
        for i in range(0, size_A[0]):
            for j in range(0, size_B[1]):
                print(i, j, B[i][j])
            
        return 0 #(multiplication_of_A_and_B)
    

A = [[1, 2], [3, 4]]
B = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]
result = matrix_mul(A, B)
print(result)

0 0 1
0 1 2
0 2 3
0 3 4
0 4 5
1 0 5
1 1 6
1 2 7
1 3 8
1 4 9
0


In [ ]:

import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure

list1=[0, 5 ,27, 6, 13, 28, 100, 45, 10,79]   

def pick_a_number_from_list(A):
    weights1=[]
    
    for i in A:
        weights1.append(i/sum(list1))
        
    selected_random_number = random.choices(A,weights=weights1,k=1)    
    
    return selected_random_number


def sampling_based_on_magnitued():
    for i in range(1,100):
        number=pick_a_number_from_list(list1)
        print(number)
    

sampling_based_on_magnitued()

[28]
[100]
[100]
[27]
[27]
[100]
[27]
[100]
[100]
[79]
[79]
[27]
[79]
[79]
[79]
[45]
[28]
[10]
[27]
[100]
[100]
[100]
[45]
[100]
[79]
[79]
[45]
[79]
[100]
[100]
[45]
[100]
[100]
[10]
[45]
[100]
[6]
[13]
[45]
[79]
[45]
[79]
[27]
[27]
[27]
[100]
[27]
[45]
[100]
[79]
[28]
[28]
[28]
[100]
[27]
[28]
[27]
[100]
[27]
[28]
[10]
[100]
[10]
[28]
[100]
[28]
[100]
[45]
[45]
[100]
[79]
[100]
[100]
[28]
[28]
[100]
[45]
[27]
[100]
[45]
[79]
[28]
[100]
[79]
[79]
[100]
[79]
[100]
[79]
[79]
[27]
[45]
[79]
[100]
[27]
[100]
[6]
[100]
[27]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    # 
     # modified string which is after replacing the # with digits
    string_list = []
    for i in range(len(String)):
      string_list.append(String[i])

    result = [] 
    for string in string_list:
      if string.isdigit():
        string_list.remove(string)
        result.append("#")
    return result
  
replace_digits("abc")

[]

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
import math

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

# zip will bind together students with corresponding marks as a list of tuples
grades = list(zip(Students, Marks))

# sort the list of tuples on the grades, so selecting the second element (index 1) of the tuple  
grades.sort(key = lambda e: e[1])
#print(grades)

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    # Use slicing on 'grades' list of tuples
    top_5 = grades[5:]
    top = top_5[::-1]
    top_5_students = top
    # write code for computing top least 5 students
    least = grades[:5]
    least_5_students = least
    # write code for computing marks between 25th percentile and 75th percentile
    # Slice out 25th percentile and 75th percentile based on the length of the 'grades' list
    twenty_fifth = math.ceil(len(grades) // 4)
    seventy_fifth = math.floor(3 * len(grades) // 4)
    middle = grades[twenty_fifth:seventy_fifth]
    students_within_25_and_75 = middle# compute this
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)

[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
[('student9', 35), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
cosine_dist = []
S = [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
P = (3,-4)

# To find out the inverse of cosine in Python we use math.acos() function of Python Standard math Library. 
# The inverse of cosine is also called arc cosine.
for a, b in S:
    numerator = a * P[0] + b * P[1]
    denominator = math.sqrt(a ** 2 + b ** 2) * math.sqrt(P[0] ** 2 + P[1] **2)       
    cosine_dist.append(math.acos(numerator / denominator))

X = cosine_dist
Y = [S for S in sorted(zip(S,X), key = lambda i: i[1])]
k = Y[:5] 
for i, j in k:
    print(i)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
    
# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    sign_of_r_pts_eq = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_of_r_pts_eq = 1

    for r_pt in red:
        if sign_of_r_pts_eq == 1 and eval(
                line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) < 0:
            return 'NO'

        if sign_of_r_pts_eq == -1 and eval(
                line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) > 0:
            return 'NO'


    sign_of_b_pts_eq = -1 * sign_of_r_pts_eq

    for b_pts in blue:
        if sign_of_b_pts_eq == 1 and eval(
                line.replace('x', '*%s' % b_pts[0]).replace('y', '*%s' % b_pts[1])) < 0:
            return 'NO'

        if sign_of_b_pts_eq == -1 and eval(
                line.replace('x', '*%s' % b_pts[0]).replace('y', '*%s' % b_pts[1])) > 0:
            return 'NO'

    return 'YES'

Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]

Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

def curve_smoothing(string):
    # your code
    index_of_non_empty_cells_list = []

    split_string = string.split(',')
    
    for i in range(len(split_string)):
        if split_string[i] != '_':
            index_of_non_empty_cells_list.append(i)
            
    # add the length of the original list to index_of_non_empty_cells_list
    index_of_non_empty_cells_list.append(len(split_string) - 1)
    
    #print(index_of_non_empty_cells_list)
    
    # Loop over the index_of_non_empty_cells_list to modify the original list by filling up empty slots
    
    start = 0
    
    for ele in index_of_non_empty_cells_list:
        # Whenever there is a missing value, add the proceeding value and the immediately next available value
        # and divide it by the number of missing values.
        # Calculate the cumulative_sum of available non-empty cells.
        cumulative_sum_prev_and_next_value = int(split_string[ele]) if split_string[ele] != '_' else 0
        cumulative_sum_prev_and_next_value += int(split_string[start]) if split_string[start] != '_' and start != ele else 0
#       print(cumulative_sum_prev_and_next_value)
        # Divide the cumulative_sum of prev and next value by the number of missing values
        integer_to_replace = cumulative_sum_prev_and_next_value // (ele - start + 1)
        split_string = [integer_to_replace if start <= x <= ele else split_string[x] for x in range(len(split_string))]
        start = ele
    return split_string#list of values

S =  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(F, S):
    # your code
    numerator = 0
    denominator = 0
    for i in range(len(A)):
        if(A[i][1] == S):
            denominator = denominator + 1
            if(A[i][0] == F):
                numerator = numerator + 1
    print('P(F = {} | S == {}) = {}/{}'.format(F, S, str(numerator), str(denominator)))
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

for i in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for j in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(i, j)

P(F = F1 | S == S1) = 1/4
P(F = F1 | S == S2) = 1/3
P(F = F1 | S == S3) = 0/3
P(F = F2 | S == S1) = 1/4
P(F = F2 | S == S2) = 1/3
P(F = F2 | S == S3) = 1/3
P(F = F3 | S == S1) = 0/4
P(F = F3 | S == S2) = 1/3
P(F = F3 | S == S3) = 1/3
P(F = F4 | S == S1) = 1/4
P(F = F4 | S == S2) = 0/3
P(F = F4 | S == S3) = 1/3
P(F = F5 | S == S1) = 1/4
P(F = F5 | S == S2) = 0/3
P(F = F5 | S == S3) = 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    # Split the words of the sentences and put the words in a set
    S1_words = set(S1.split())
    S2_words = set(S2.split())
    # Use set intersection operation to get the common words between 2 sets and compute the length of the resultant set
    a = len(S1_words & S2_words)
    # Use set difference operation to get the words that present in either of the set and display the words as a list
    b = set(S1_words) - (set(S2_words))
    b_l = list(b)
    c = set(S2_words) - (set(S1_words))
    c_l = list(c)
    return a, b_l, c_l

S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
a, b_l, c_l = string_features(S1, S2)
print(a)
print(b_l)
print(c_l)

7
['5', 'F', 'first']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
from math import log
def compute_log_loss(A):
    # your code
    loss = 0
    for row in A:
        loss += (row[0] * log(row[1], 10)) + ((1 - row[0]) * log(1 - row[1], 10))
        log_loss = -1 * loss / len(A)
    return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
